const skill = {
    data: [{
        name: "C",
        value: "10"
    }, {
        name: "C++",
        value: "10"
    }, {
        name: "Java",
        value: "8"
    }, {
        name: "JavaScript",
        value: "4"
    }, {
        name: 'HTML5',
        value: '3'
    }, {
        name: 'CSS3',
        value: '3'
    }, {
        name: "ES6",
        value: "4"
    }, {
        name: 'pug',
        value: '2'
    }, {
        name: 'Sass',
        value: '2'
    }, {
        name: "TypeScript",
        value: "2"
    }, {
        name: 'webpack',
        value: '2'
    }, {
        name: 'Gulp',
        value: '1'
    }, {
        name: 'JSON',
        value: '2'
    }, {
        name: 'Vue',
        value: '3'
    }, {
        name: 'Node.js',
        value: '3'
    }, {
        name: 'Express',
        value: '2'
    }, {
        name: 'Koa',
        value: '2'
    }, {
        name: '微信小程序',
        value: '1'
    }, {
        name: "Python",
        value: "4"
    }, {
        name: 'scrapy',
        value: '3'
    }, {
        name: 'HTTP',
        value: '3'
    }, {
        name: 'XML',
        value: '1'
    }, {
        name: '驱动开发',
        value: '2'
    }, {
        name: '51单片机',
        value: '1'
    }, {
        name: 'STM32树莓派',
        value: '1'
    }, {
        name: 'ardinuo',
        value: '2'
    }, {
        name: 'Linux',
        value: '3'
    }, {
        name: 'ZigBee',
        value: '2'
    }, {
        name: 'Unix',
        value: '2'
    }, {
        name: 'FPGA',
        value: '2'
    }, {
        name: '模拟电路',
        value: '2'
    }, {
        name: '数字电路',
        value: '2'
    }, {
        name: 'Tomcat',
        value: '2'
    }, {
        name: 'MySQL',
        value: '3'
    }, {
        name: 'Redis',
        value: '2'
    }, {
        name: 'SpingMVC',
        value: '2'
    }, {
        name: 'Hibernate',
        value: '1'
    }, {
        name: 'Mybatis',
        value: '1'
    }, {
        name: 'Security',
        value: '2'
    }, {
        name: 'Shiro',
        value: '2'
    }, {
        name: 'ehcache',
        value: '1'
    }, {
        name: 'Nginx',
        value: '3'
    }, {
        name: 'Kotlin',
        value: '3'
    }, {
        name: 'Android',
        value: '4'
    }, {
        name: 'MVP',
        value: '2'
    }, {
        name: 'MVVM',
        value: '3'
    }, {
        name: 'MaterialDesign',
        value: '2'
    }, {
        name: 'OKhttp Retrofit',
        value: '2'
    }, {
        name: 'Gson',
        value: '2'
    }, {
        name: 'realm',
        value: '1'
    }, {
        name: 'greendao',
        value: '1'
    }, {
        name: 'butterknife',
        value: '1'
    }]
};

module.exports = skill;